### ISSUE TITLE
Have Bibliography::parse return Result instead of Option?

### ISSUE THREAD

**Issue by ariroffe** [typst/biblatex#15]
Hi, I'm the author of this crate, which uses biblatex: [https://github.com/ariroffe/bib-unifier](https://github.com/ariroffe/bib-unifier)

I was testing it with some real files, which some colleagues gave me, and `Bibliography::parse` was returning `None` and failing to parse some of them. I managed to track down the issue to the following entry, which those files contained:

```
@inproceedings{conigliocorbalan,
  author    = {Marcelo Coniglio and Mar{\'{\i}}a I. Corbal{\'{a}}n},
  title     = {Sequent Calculi for the classical fragment of {B}ochvar and {H}alld{\'{e}}n's {N}onsense {L}ogics},
  booktitle = {Proceedings Seventh Workshop on Logical and Semantic Frameworks, with Applications, {LSFA} 2012, Rio de Janeiro, Brazil, September 29-30, 2012.},
  pages     = {125--136},
  year      = {2012},
}
```

The problem is merely that there is an extra `\` before the i in `Mar{\'{\i}}a`. When that backlash is removed, the files parse correctly.

The thing is, `parse` was failing completely, without any explanation as to why, so all I can tell the end user is that there was a problem parsing that file. I'm new to Rust, and maybe this too much to ask, but would it not be more appropriate if `parse` returned a `Result` instead of an `Option`? (or at least to have another method that does return a `Result`). The `Err` variant could then detail which part of the original file was the cause of the parsing failure. I believe this could help users of the library such as myself.

**Comment by ariroffe** [comment]
See #16

**Comment by reknih** [comment]
The error reporting in biblatex is crap right now.

A rewrite of the whole parser is definitely on the slate and one priority for me is to provide good diagnostics that point to the actual syntax error (i.e. `unexpected ' after backslash on line 1`).

Until that happens however, your PR definitely provides a good quick fix that works with the current infrastructure.
