### ISSUE TITLE
Parsing error on unprotected numbers

### ISSUE THREAD

**Issue by aurelien-naldi** [typst/biblatex#23]
The following bibtex is valid but trigger a parsing error (```unknown abbreviation "2020": 274-278```):

```bibtex
@article{bullshit2020,
    title={At-scale impact of the {Net Wok}: A culinarically holistic investigation of distributed dumplings},
    author={Astley, Rick and Morris, Linda},
    journal={Armenian Journal of Proceedings},
    volume={61},
    pages={192--219},
    year=2020,
    publisher={Automattic Inc.}
  }
```

The problem comes from the value of the "year" field which is not enclosed (which is allowed in bibltex and found in many places).

**Comment by reknih** [comment]
Thank you for filing this bug! The rewrite of the parser caused this regression (and it also caused the test suite to regress and not test this due to a missing `.unwrap`). I will push a fix and a release.
