### ISSUE TITLE
Pages and volume parse errors

### ISSUE THREAD

**Issue by ivomac** [typst/biblatex#29]
I'm moving here the issue typst/typst#210. 

Compilation fails if the bibliography (.bib) file has an entry such as this:

```
@article{1,
    title = {A},
    number = {B4},
    pages = {B97},
    volume = {40-42},
    price = {$76.60}
}
```

Parse errors due to letters ("B") in pages and "-" in volume. Also fails on `price` with unexpected end of file due to the dollar. No error due to "B" in number.

I think this entry should be valid as I have official bib entries with ranges on `volume` and letters on `pages`.

**Comment by rudolfsg** [comment]
Came across this issue as I had problems with dollar signs in the bib file myself. I just tried the example .bib entry that @ivomac posted and typst fails with `unexpected end of file` so I think it should be reopened
