### ISSUE TITLE
Support `/` as an entry key delimiter

### ISSUE THREAD

**Issue by Neved4** [typst/biblatex#33]
A BibLaTeX entry key, of the form `name1/name2` currently fails:

```bib
@online{baez/online,
  author       = {Baez, John C. and Lauda, Aaron D.},
  title        = {Higher-Dimensional Algebra {V}: 2-Groups},
  date         = {2004-10-27},
  version      = 3,
  langid       = {english},
  langidopts   = {variant=american},
  eprinttype   = {arxiv},
  eprint       = {math/0307200v3},
}
```

Reference: [biblatex-examples.bib](https://raw.githubusercontent.com/plk/biblatex/dev/bibtex/bib/biblatex/biblatex-examples.bib)

**Comment by zepinglee** [comment]
The `/` character here is not a delimiter. Actually it has no special meaning.

The entry key in the original BibTeX only forbids `,`, `}`, and whitespaces in a brace-style entry, or `,` plus whitespaces in a parenthesis style entry (see [aclements/biblib](https://github.com/aclements/biblib#recognized-grammar)). The following are valid entry keys for BibTeX. Although some characters (e.g., `#` and `\`) are not allowed in a LaTeX `\cite` command, the entries can still be `crossref`ed or listed out with `\nocite{*}`.

```bib
@misc{!"#$%&'()*+-./123:;<=>?@ABC[\]^_`abc{|~,
  author = {John Doe},
}

@misc(!"#$%&')(*+-./123:;<=>?@ABC[\]^_`abc{|}~,
  author = {John Doe},
)
```

Biber, which uses `btparse` as the underlying parser, only allows letters, digits, and the following characters in entry key: ``! $ & * + - . / : ; < > ? [ ] ^ _ ` |`` (see [Text-BibTeX/btparse](https://metacpan.org/dist/Text-BibTeX/view/btparse/doc/btparse.pod#CONCEPTS-AND-TERMINOLOGY)).

**Comment by reknih** [comment]
Thank you!
