### ISSUE TITLE
Formulas are rendered incorrectly

### ISSUE THREAD

**Issue by ice1000** [typst/biblatex#35]
![image](https://github.com/typst/biblatex/assets/16398479/72415a22-209b-4ca8-bc41-ff03b12ef0a1)

Source:
```bibtex
@article{NewBrunerie,
  title = {Formalizing $π_4(bb(S)^3) ≅ bb(Z)/(2 bb(Z))$ and Computing a Brunerie Number in Cubical Agda},
  author = {Axel Ljungström and Anders Mörtberg},
  year = 2023,
  url = {https://arxiv.org/abs/2210.08232},
}
```

I wish the formula can be rendered as typst code.

**Comment by reknih** [comment]
![Example with rendered formula](https://github.com/typst/biblatex/assets/3874949/2fde6f38-3b27-46a4-8a40-34ff628739dd)

Typst 0.9.0 has you covered, bro/sis

**Comment by ice1000** [comment]
> ![Example with rendered formula](https://user-images.githubusercontent.com/3874949/285250385-2fde6f38-3b27-46a4-8a40-34ff628739dd.png)
> 
> Typst 0.9.0 has you covered, bro/sis

Tooooooooo goooooooooooooooooood!!!!!!!!!!!
Yeeeaaaaahhhhhhhhhhhhhhhhhhhhhhhhhh!!!!!!!!!!!!!!!!!!!!!!!!!
