### ISSUE TITLE
-- and --- aren't turned into en and em-dashes in the bibliography

### ISSUE THREAD

**Issue by Enivex** [typst/biblatex#49]
### Description

```
@Article{Doe58Knitting,
  author  = {Doe, John},
  journal = {International Journal of Underwater Basket Weaving},
  title   = {Knitting A--Z --- A practical guide},
  year    = {1958},
}
```
is rendered as
![image](https://github.com/typst/typst/assets/2191754/163b84c2-2bcd-46c7-9341-6d209e5accf0)

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
No news atm, but it should be rather simple to do if someone wants to pick it up.

**Comment by Enivex** [comment]
I might add that for the time being you can put literal unicode en- and em-dashes in there.
